TARGET_ARCH := arm
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi

TARGET_BOOTLOADER_BOARD_NAME := mt6739
TARGET_BOARD_PLATFORM := mt6739

TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

BOARD_KERNEL_IMAGE_NAME := zImage
BOARD_KERNEL_CMDLINE := bootopt=64S3,32N2,64N2

TARGET_COPY_OUT_VENDOR := vendor

include vendor/samsung/a02/BoardConfigVendor.mk
